import Foundation

public enum BasicPDFExportAdapter {
    public static func render(project: DreamJotterProject, preset: ExportPreset, generatedAt: Date = Date()) -> Data {
        let text = pdfText(for: project, preset: preset, generatedAt: generatedAt)
        let content = pdfContentStream(for: text)
        let contentLength = content.utf8.count

        let objects = [
            "<< /Type /Catalog /Pages 2 0 R >>",
            "<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
            "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>",
            "<< /Length \(contentLength) >>\nstream\n\(content)\nendstream",
            "<< /Type /Font /Subtype /Type1 /BaseFont /Courier >>"
        ]

        var pdf = "%PDF-1.4\n"
        var offsets: [Int] = [0]
        for (index, object) in objects.enumerated() {
            offsets.append(pdf.utf8.count)
            pdf += "\(index + 1) 0 obj\n\(object)\nendobj\n"
        }

        let xrefOffset = pdf.utf8.count
        pdf += "xref\n0 \(objects.count + 1)\n"
        pdf += "0000000000 65535 f \n"
        for offset in offsets.dropFirst() {
            pdf += String(format: "%010d 00000 n \n", offset)
        }
        pdf += "trailer\n<< /Size \(objects.count + 1) /Root 1 0 R >>\n"
        pdf += "startxref\n\(xrefOffset)\n%%EOF\n"
        return Data(pdf.utf8)
    }

    private static func pdfText(for project: DreamJotterProject, preset: ExportPreset, generatedAt: Date) -> [String] {
        var lines = [
            project.metadata.title,
            "",
            FountainIO.exportScreenplay(project.screenplay)
        ].joined(separator: "\n").components(separatedBy: .newlines)

        if preset.includesNotes, !project.notes.isEmpty {
            lines.append("")
            lines.append("NOTES")
            lines.append(contentsOf: project.notes.map { "- \($0.body)" })
        }

        if preset.includesAppVersion {
            lines.append("")
            lines.append("Generated by DreamJotter at \(ISO8601DateFormatter().string(from: generatedAt))")
        }

        return lines
    }

    private static func pdfContentStream(for lines: [String]) -> String {
        var commands = ["BT", "/F1 12 Tf", "72 740 Td"]
        var isFirstLine = true
        for line in lines.prefix(54) {
            if isFirstLine {
                isFirstLine = false
            } else {
                commands.append("0 -13 Td")
            }
            commands.append("(\(escapedPDFString(line))) Tj")
        }
        commands.append("ET")
        return commands.joined(separator: "\n")
    }

    private static func escapedPDFString(_ value: String) -> String {
        var escaped = ""
        for scalar in value.unicodeScalars {
            switch scalar {
            case "\\":
                escaped += "\\\\"
            case "(":
                escaped += "\\("
            case ")":
                escaped += "\\)"
            case "\n", "\r", "\t":
                escaped += " "
            default:
                if scalar.value < 32 {
                    escaped += " "
                } else {
                    escaped.append(Character(scalar))
                }
            }
        }
        return escaped
    }
}
